Update intro_vectors.ipynb
For this part, at the bottom of the notebook :
        x = np.array(np.range(1,5))**2
Maybe we should use 
       x = np.array(range(1,5))**2
cause" AttributeError: module 'numpy' has no attribute 'range' "